### ISSUE TITLE
Clean up the main class

### ISSUE THREAD

**Issue by Lignum** [justync7/ytci-krist-miner-gpu#5]
The main class really shouldn't be responsible for that many things, especially that main method is a giant mess.

**Comment by dmarcuse** [comment]
I cleaned it up a bit by switching to commons-cli for argument parsing, but I agree. We won't be using the CPU mining code most likely anyways, so I say we cut it out of the main class entirely.

**Comment by Lustyn** [comment]
Agreed.

**Comment by dmarcuse** [comment]
I'll work on this once I get back from dinner. I'll be working in the "apemanzilla" branch.

**Comment by Lustyn** [comment]
Alright.

**Comment by Lignum** [comment]
@apemanzilla Damn, you're quick. I was working on getting commons-cli in as well. I think I have a cleaner solution though that reduces code in the main method, would you mind if I replaced yours with it?

EDIT: Here's what I was working on: http://pastebin.com/vu0CxbMa

**Comment by dmarcuse** [comment]
That's fine, does this mean we're scrapping the main method and rewriting it from scratch?

**Comment by Lignum** [comment]
Alright, I'll get started on that. While I won't be rewriting the main method right now, it's definitely something that needs to be done. Right now, KristMiner is pretty much a god object, which really needs to be solved by splitting it up into several classes, I suppose.

**Comment by dmarcuse** [comment]
I feel like the main bulk of the class is the CPU mining code - which we don't need (I mean, we could do dual-mining, but I think that GPU is the main focus right now anyways) so just removing that should clean it up a lot.

**Comment by Lustyn** [comment]
Honestly, dual-mining will overall slow down the process. It'd be better to stick to fresh code.

**Comment by dmarcuse** [comment]
I've stripped out most of the old code for CPU mining from the main class. Anything else we should do with it?

**Comment by Lignum** [comment]
Awesome, it looks much better now! One last thing that I find needs to be done is to move all that code into a separate class, which should be a matter of copy & paste, and make it a bit more object oriented by getting rid of all that `static` voodoo (maybe make the class a singleton?).

**Comment by Lignum** [comment]
That commit should also help with integrating the miner into the GUI. Though I also want to make some changes to `KristConfig` to not be console-bound anymore to make it even more reusable.

**Comment by dmarcuse** [comment]
Progress: 202924a2379f0ec7d8c4f50d128203cd6a779237

Now the GUI will create a KristMiner object with a KristConfig object.

I may write a separate thread - one for the GUI itself, one to act as an async middleman between the GUI and KristMiner - this way, the GUI won't lockup (for example, when getting the syncnode)

**Comment by Lignum** [comment]
I think we've pretty much cleaned up the main class beyond recognition, so I'll close this issue for now.
