### ISSUE TITLE
Missing opencl_cryptsha256.h

### ISSUE THREAD

**Issue by Lignum** [justync7/ytci-krist-miner-gpu#9]
`cryptsha256_kernel_GPU.cl` appears to be including a file that is missing.
Line 14: `#include "opencl_cryptsha256.h"`

**Comment by dmarcuse** [comment]
[This](https://github.com/magnumripper/JohnTheRipper/blob/bleeding-jumbo/src/opencl_cryptsha256.h)? Although that in turn includes a bunch of other files we don't have...

Would it be easier to try to re-use the code from the Bitcoin miner [DiabloMiner](https://github.com/Diablo-D3/DiabloMiner/blob/master/src/main/resources/DiabloMiner.cl)? Written in Java with OpenCL and LWJGL...

**Comment by Lustyn** [comment]
That would probably make it pretty optimized aready, and not require as much hackery done to it. I recommend we switch to that.

**Comment by Lustyn** [comment]
But the only problem is that is opimized for bitcoin, so were going to have to make it sha256(x) instead of sha256(sha256(x))

**Comment by dmarcuse** [comment]
Well, as I said earlier, I don't know much about OpenCL, so it's up to you - whichever you think will be easiest.

**Comment by Lustyn** [comment]
We won't be using cryptsha256_kernel_GPU.cl anymore.
